import type { ProjectCostSummary } from "../types/projects.types";

// PLACEHOLDER: static data used until GET /api/admin/projects/{id}/cost-summary is implemented
export const STATIC_COST_SUMMARY: ProjectCostSummary = {
  projectId:               1,
  healthStatus:            "AT_RISK",
  budget:                  50000,
  totalCost:               41200,
  totalSalaryCost:         34800,
  totalManualCost:         6400,
  budgetUtilizationPct:    82.4,
  budgetVariance:          8800,
  projectedFinalCost:      56000,
  projectedVariance:       -6000,
  revenueTarget:           60000,
  actualRevenue:           null,
  grossMargin:             null,
  marginPct:               null,
  dailyBurnRate:           820,
  weeklyBurnRateRolling:   4200,
  weeklyBurnRateAverage:   3900,
  activeDays:              50,
  overtimeDelta:           1240,
  normalOtExtra:           840,
  specialOtExtra:          400,
  overtimePctOfSalaryCost: 8.2,
  employeeCosts: [
    {
      employeeId:     101,
      employeeName:   "Ahmed Hassan",
      employmentType: "FULL_TIME",
      totalHours:     320,
      regularHours:   300,
      overtimeHours:  20,
      salaryCost:     16200,
      costStatus:     "ESTIMATED",
    },
    {
      employeeId:     102,
      employeeName:   "Sara El-Masry",
      employmentType: "FULL_TIME",
      totalHours:     280,
      regularHours:   270,
      overtimeHours:  10,
      salaryCost:     14100,
      costStatus:     "ESTIMATED",
    },
    {
      employeeId:     103,
      employeeName:   "Omar Youssef",
      employmentType: "PART_TIME",
      totalHours:     90,
      regularHours:   90,
      overtimeHours:  0,
      salaryCost:     4500,
      costStatus:     "CONFIRMED",
    },
  ],
};
