/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeeRouteImport } from './routes/_employee'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as EmployeeIndexRouteImport } from './routes/_employee/index'
import { Route as EmployeeProjectsRouteImport } from './routes/_employee/projects'
import { Route as EmployeeAttendanceRouteImport } from './routes/_employee/attendance'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminProjectsRouteImport } from './routes/_admin/admin.projects'
import { Route as AdminAdminPermissionsRouteImport } from './routes/_admin/admin.permissions'
import { Route as AdminAdminEmployeesRouteImport } from './routes/_admin/admin.employees'
import { Route as AdminAdminAttendanceRouteImport } from './routes/_admin/admin.attendance'
import { Route as AdminAdminProjectsIndexRouteImport } from './routes/_admin/admin.projects.index'
import { Route as AdminAdminEmployeesIndexRouteImport } from './routes/_admin/admin.employees.index'
import { Route as AdminAdminProjectsProjectIdRouteImport } from './routes/_admin/admin.projects.$projectId'
import { Route as AdminAdminEmployeesEmployeeIdRouteImport } from './routes/_admin/admin.employees.$employeeId'

const EmployeeRoute = EmployeeRouteImport.update({
  id: '/_employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProjectsRoute = EmployeeProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => EmployeeRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProjectsRoute = AdminAdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPermissionsRoute = AdminAdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEmployeesRoute = AdminAdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAttendanceRoute = AdminAdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProjectsIndexRoute = AdminAdminProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminProjectsRoute,
} as any)
const AdminAdminEmployeesIndexRoute =
  AdminAdminEmployeesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminEmployeesRoute,
  } as any)
const AdminAdminProjectsProjectIdRoute =
  AdminAdminProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AdminAdminProjectsRoute,
  } as any)
const AdminAdminEmployeesEmployeeIdRoute =
  AdminAdminEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AdminAdminEmployeesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof EmployeeIndexRoute
  '/login': typeof AuthLoginRoute
  '/attendance': typeof EmployeeAttendanceRoute
  '/projects': typeof EmployeeProjectsRoute
  '/admin/attendance': typeof AdminAdminAttendanceRoute
  '/admin/employees': typeof AdminAdminEmployeesRouteWithChildren
  '/admin/permissions': typeof AdminAdminPermissionsRoute
  '/admin/projects': typeof AdminAdminProjectsRouteWithChildren
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/employees/$employeeId': typeof AdminAdminEmployeesEmployeeIdRoute
  '/admin/projects/$projectId': typeof AdminAdminProjectsProjectIdRoute
  '/admin/employees/': typeof AdminAdminEmployeesIndexRoute
  '/admin/projects/': typeof AdminAdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof EmployeeIndexRoute
  '/login': typeof AuthLoginRoute
  '/attendance': typeof EmployeeAttendanceRoute
  '/projects': typeof EmployeeProjectsRoute
  '/admin/attendance': typeof AdminAdminAttendanceRoute
  '/admin/permissions': typeof AdminAdminPermissionsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/employees/$employeeId': typeof AdminAdminEmployeesEmployeeIdRoute
  '/admin/projects/$projectId': typeof AdminAdminProjectsProjectIdRoute
  '/admin/employees': typeof AdminAdminEmployeesIndexRoute
  '/admin/projects': typeof AdminAdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_employee': typeof EmployeeRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_employee/attendance': typeof EmployeeAttendanceRoute
  '/_employee/projects': typeof EmployeeProjectsRoute
  '/_employee/': typeof EmployeeIndexRoute
  '/_admin/admin/attendance': typeof AdminAdminAttendanceRoute
  '/_admin/admin/employees': typeof AdminAdminEmployeesRouteWithChildren
  '/_admin/admin/permissions': typeof AdminAdminPermissionsRoute
  '/_admin/admin/projects': typeof AdminAdminProjectsRouteWithChildren
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/employees/$employeeId': typeof AdminAdminEmployeesEmployeeIdRoute
  '/_admin/admin/projects/$projectId': typeof AdminAdminProjectsProjectIdRoute
  '/_admin/admin/employees/': typeof AdminAdminEmployeesIndexRoute
  '/_admin/admin/projects/': typeof AdminAdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/projects'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/permissions'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/'
    | '/admin/employees/$employeeId'
    | '/admin/projects/$projectId'
    | '/admin/employees/'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/attendance'
    | '/projects'
    | '/admin/attendance'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin'
    | '/admin/employees/$employeeId'
    | '/admin/projects/$projectId'
    | '/admin/employees'
    | '/admin/projects'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_employee'
    | '/_auth/login'
    | '/_employee/attendance'
    | '/_employee/projects'
    | '/_employee/'
    | '/_admin/admin/attendance'
    | '/_admin/admin/employees'
    | '/_admin/admin/permissions'
    | '/_admin/admin/projects'
    | '/_admin/admin/settings'
    | '/_admin/admin/'
    | '/_admin/admin/employees/$employeeId'
    | '/_admin/admin/projects/$projectId'
    | '/_admin/admin/employees/'
    | '/_admin/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_employee': {
      id: '/_employee'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_employee/': {
      id: '/_employee/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/projects': {
      id: '/_employee/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof EmployeeProjectsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/attendance': {
      id: '/_employee/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/projects': {
      id: '/_admin/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminAdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/permissions': {
      id: '/_admin/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminAdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/employees': {
      id: '/_admin/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminAdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/attendance': {
      id: '/_admin/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/projects/': {
      id: '/_admin/admin/projects/'
      path: '/'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminAdminProjectsIndexRouteImport
      parentRoute: typeof AdminAdminProjectsRoute
    }
    '/_admin/admin/employees/': {
      id: '/_admin/admin/employees/'
      path: '/'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminAdminEmployeesIndexRouteImport
      parentRoute: typeof AdminAdminEmployeesRoute
    }
    '/_admin/admin/projects/$projectId': {
      id: '/_admin/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminAdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminAdminProjectsRoute
    }
    '/_admin/admin/employees/$employeeId': {
      id: '/_admin/admin/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/admin/employees/$employeeId'
      preLoaderRoute: typeof AdminAdminEmployeesEmployeeIdRouteImport
      parentRoute: typeof AdminAdminEmployeesRoute
    }
  }
}

interface AdminAdminEmployeesRouteChildren {
  AdminAdminEmployeesEmployeeIdRoute: typeof AdminAdminEmployeesEmployeeIdRoute
  AdminAdminEmployeesIndexRoute: typeof AdminAdminEmployeesIndexRoute
}

const AdminAdminEmployeesRouteChildren: AdminAdminEmployeesRouteChildren = {
  AdminAdminEmployeesEmployeeIdRoute: AdminAdminEmployeesEmployeeIdRoute,
  AdminAdminEmployeesIndexRoute: AdminAdminEmployeesIndexRoute,
}

const AdminAdminEmployeesRouteWithChildren =
  AdminAdminEmployeesRoute._addFileChildren(AdminAdminEmployeesRouteChildren)

interface AdminAdminProjectsRouteChildren {
  AdminAdminProjectsProjectIdRoute: typeof AdminAdminProjectsProjectIdRoute
  AdminAdminProjectsIndexRoute: typeof AdminAdminProjectsIndexRoute
}

const AdminAdminProjectsRouteChildren: AdminAdminProjectsRouteChildren = {
  AdminAdminProjectsProjectIdRoute: AdminAdminProjectsProjectIdRoute,
  AdminAdminProjectsIndexRoute: AdminAdminProjectsIndexRoute,
}

const AdminAdminProjectsRouteWithChildren =
  AdminAdminProjectsRoute._addFileChildren(AdminAdminProjectsRouteChildren)

interface AdminRouteChildren {
  AdminAdminAttendanceRoute: typeof AdminAdminAttendanceRoute
  AdminAdminEmployeesRoute: typeof AdminAdminEmployeesRouteWithChildren
  AdminAdminPermissionsRoute: typeof AdminAdminPermissionsRoute
  AdminAdminProjectsRoute: typeof AdminAdminProjectsRouteWithChildren
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAttendanceRoute: AdminAdminAttendanceRoute,
  AdminAdminEmployeesRoute: AdminAdminEmployeesRouteWithChildren,
  AdminAdminPermissionsRoute: AdminAdminPermissionsRoute,
  AdminAdminProjectsRoute: AdminAdminProjectsRouteWithChildren,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface EmployeeRouteChildren {
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeProjectsRoute: typeof EmployeeProjectsRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeProjectsRoute: EmployeeProjectsRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
