/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeeRouteImport } from './routes/_employee'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as EmployeeIndexRouteImport } from './routes/_employee/index'
import { Route as EmployeeProjectsRouteImport } from './routes/_employee/projects'
import { Route as EmployeePayslipsRouteImport } from './routes/_employee/payslips'
import { Route as EmployeeLeaveRouteImport } from './routes/_employee/leave'
import { Route as EmployeeAttendanceRouteImport } from './routes/_employee/attendance'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as EmployeePayslipsIndexRouteImport } from './routes/_employee/payslips.index'
import { Route as EmployeeAttendanceIndexRouteImport } from './routes/_employee/attendance.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as EmployeeAttendanceLogRouteImport } from './routes/_employee/attendance.log'
import { Route as EmployeeAttendanceDateRouteImport } from './routes/_employee/attendance.$date'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminProjectsRouteImport } from './routes/_admin/admin.projects'
import { Route as AdminAdminPayrollRouteImport } from './routes/_admin/admin.payroll'
import { Route as AdminAdminLeaveRouteImport } from './routes/_admin/admin.leave'
import { Route as AdminAdminEmployeesRouteImport } from './routes/_admin/admin.employees'
import { Route as AdminAdminAttendanceRouteImport } from './routes/_admin/admin.attendance'
import { Route as AdminAdminProjectsIndexRouteImport } from './routes/_admin/admin.projects.index'
import { Route as AdminAdminPayrollIndexRouteImport } from './routes/_admin/admin.payroll.index'
import { Route as AdminAdminEmployeesIndexRouteImport } from './routes/_admin/admin.employees.index'
import { Route as EmployeePayslipsYearMonthRouteImport } from './routes/_employee/payslips.$year.$month'
import { Route as AdminAdminProjectsProjectIdRouteImport } from './routes/_admin/admin.projects.$projectId'
import { Route as AdminAdminEmployeesEmployeeIdRouteImport } from './routes/_admin/admin.employees.$employeeId'
import { Route as AdminAdminPayrollYearMonthRouteImport } from './routes/_admin/admin.payroll.$year.$month'

const EmployeeRoute = EmployeeRouteImport.update({
  id: '/_employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProjectsRoute = EmployeeProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePayslipsRoute = EmployeePayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLeaveRoute = EmployeeLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => EmployeeRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const EmployeePayslipsIndexRoute = EmployeePayslipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeePayslipsRoute,
} as any)
const EmployeeAttendanceIndexRoute = EmployeeAttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeAttendanceRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeAttendanceLogRoute = EmployeeAttendanceLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => EmployeeAttendanceRoute,
} as any)
const EmployeeAttendanceDateRoute = EmployeeAttendanceDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => EmployeeAttendanceRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProjectsRoute = AdminAdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPayrollRoute = AdminAdminPayrollRouteImport.update({
  id: '/admin/payroll',
  path: '/admin/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLeaveRoute = AdminAdminLeaveRouteImport.update({
  id: '/admin/leave',
  path: '/admin/leave',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEmployeesRoute = AdminAdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAttendanceRoute = AdminAdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProjectsIndexRoute = AdminAdminProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminProjectsRoute,
} as any)
const AdminAdminPayrollIndexRoute = AdminAdminPayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminPayrollRoute,
} as any)
const AdminAdminEmployeesIndexRoute =
  AdminAdminEmployeesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminEmployeesRoute,
  } as any)
const EmployeePayslipsYearMonthRoute =
  EmployeePayslipsYearMonthRouteImport.update({
    id: '/$year/$month',
    path: '/$year/$month',
    getParentRoute: () => EmployeePayslipsRoute,
  } as any)
const AdminAdminProjectsProjectIdRoute =
  AdminAdminProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AdminAdminProjectsRoute,
  } as any)
const AdminAdminEmployeesEmployeeIdRoute =
  AdminAdminEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AdminAdminEmployeesRoute,
  } as any)
const AdminAdminPayrollYearMonthRoute =
  AdminAdminPayrollYearMonthRouteImport.update({
    id: '/$year/$month',
    path: '/$year/$month',
    getParentRoute: () => AdminAdminPayrollRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof EmployeeIndexRoute
  '/login': typeof AuthLoginRoute
  '/attendance': typeof EmployeeAttendanceRouteWithChildren
  '/leave': typeof EmployeeLeaveRoute
  '/payslips': typeof EmployeePayslipsRouteWithChildren
  '/projects': typeof EmployeeProjectsRoute
  '/admin/attendance': typeof AdminAdminAttendanceRoute
  '/admin/employees': typeof AdminAdminEmployeesRouteWithChildren
  '/admin/leave': typeof AdminAdminLeaveRoute
  '/admin/payroll': typeof AdminAdminPayrollRouteWithChildren
  '/admin/projects': typeof AdminAdminProjectsRouteWithChildren
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/attendance/$date': typeof EmployeeAttendanceDateRoute
  '/attendance/log': typeof EmployeeAttendanceLogRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/attendance/': typeof EmployeeAttendanceIndexRoute
  '/payslips/': typeof EmployeePayslipsIndexRoute
  '/admin/employees/$employeeId': typeof AdminAdminEmployeesEmployeeIdRoute
  '/admin/projects/$projectId': typeof AdminAdminProjectsProjectIdRoute
  '/payslips/$year/$month': typeof EmployeePayslipsYearMonthRoute
  '/admin/employees/': typeof AdminAdminEmployeesIndexRoute
  '/admin/payroll/': typeof AdminAdminPayrollIndexRoute
  '/admin/projects/': typeof AdminAdminProjectsIndexRoute
  '/admin/payroll/$year/$month': typeof AdminAdminPayrollYearMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof EmployeeIndexRoute
  '/login': typeof AuthLoginRoute
  '/leave': typeof EmployeeLeaveRoute
  '/projects': typeof EmployeeProjectsRoute
  '/admin/attendance': typeof AdminAdminAttendanceRoute
  '/admin/leave': typeof AdminAdminLeaveRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/attendance/$date': typeof EmployeeAttendanceDateRoute
  '/attendance/log': typeof EmployeeAttendanceLogRoute
  '/admin': typeof AdminAdminIndexRoute
  '/attendance': typeof EmployeeAttendanceIndexRoute
  '/payslips': typeof EmployeePayslipsIndexRoute
  '/admin/employees/$employeeId': typeof AdminAdminEmployeesEmployeeIdRoute
  '/admin/projects/$projectId': typeof AdminAdminProjectsProjectIdRoute
  '/payslips/$year/$month': typeof EmployeePayslipsYearMonthRoute
  '/admin/employees': typeof AdminAdminEmployeesIndexRoute
  '/admin/payroll': typeof AdminAdminPayrollIndexRoute
  '/admin/projects': typeof AdminAdminProjectsIndexRoute
  '/admin/payroll/$year/$month': typeof AdminAdminPayrollYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_employee': typeof EmployeeRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_employee/attendance': typeof EmployeeAttendanceRouteWithChildren
  '/_employee/leave': typeof EmployeeLeaveRoute
  '/_employee/payslips': typeof EmployeePayslipsRouteWithChildren
  '/_employee/projects': typeof EmployeeProjectsRoute
  '/_employee/': typeof EmployeeIndexRoute
  '/_admin/admin/attendance': typeof AdminAdminAttendanceRoute
  '/_admin/admin/employees': typeof AdminAdminEmployeesRouteWithChildren
  '/_admin/admin/leave': typeof AdminAdminLeaveRoute
  '/_admin/admin/payroll': typeof AdminAdminPayrollRouteWithChildren
  '/_admin/admin/projects': typeof AdminAdminProjectsRouteWithChildren
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_employee/attendance/$date': typeof EmployeeAttendanceDateRoute
  '/_employee/attendance/log': typeof EmployeeAttendanceLogRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_employee/attendance/': typeof EmployeeAttendanceIndexRoute
  '/_employee/payslips/': typeof EmployeePayslipsIndexRoute
  '/_admin/admin/employees/$employeeId': typeof AdminAdminEmployeesEmployeeIdRoute
  '/_admin/admin/projects/$projectId': typeof AdminAdminProjectsProjectIdRoute
  '/_employee/payslips/$year/$month': typeof EmployeePayslipsYearMonthRoute
  '/_admin/admin/employees/': typeof AdminAdminEmployeesIndexRoute
  '/_admin/admin/payroll/': typeof AdminAdminPayrollIndexRoute
  '/_admin/admin/projects/': typeof AdminAdminProjectsIndexRoute
  '/_admin/admin/payroll/$year/$month': typeof AdminAdminPayrollYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/leave'
    | '/payslips'
    | '/projects'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/leave'
    | '/admin/payroll'
    | '/admin/projects'
    | '/admin/settings'
    | '/attendance/$date'
    | '/attendance/log'
    | '/admin/'
    | '/attendance/'
    | '/payslips/'
    | '/admin/employees/$employeeId'
    | '/admin/projects/$projectId'
    | '/payslips/$year/$month'
    | '/admin/employees/'
    | '/admin/payroll/'
    | '/admin/projects/'
    | '/admin/payroll/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/leave'
    | '/projects'
    | '/admin/attendance'
    | '/admin/leave'
    | '/admin/settings'
    | '/attendance/$date'
    | '/attendance/log'
    | '/admin'
    | '/attendance'
    | '/payslips'
    | '/admin/employees/$employeeId'
    | '/admin/projects/$projectId'
    | '/payslips/$year/$month'
    | '/admin/employees'
    | '/admin/payroll'
    | '/admin/projects'
    | '/admin/payroll/$year/$month'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_employee'
    | '/_auth/login'
    | '/_employee/attendance'
    | '/_employee/leave'
    | '/_employee/payslips'
    | '/_employee/projects'
    | '/_employee/'
    | '/_admin/admin/attendance'
    | '/_admin/admin/employees'
    | '/_admin/admin/leave'
    | '/_admin/admin/payroll'
    | '/_admin/admin/projects'
    | '/_admin/admin/settings'
    | '/_employee/attendance/$date'
    | '/_employee/attendance/log'
    | '/_admin/admin/'
    | '/_employee/attendance/'
    | '/_employee/payslips/'
    | '/_admin/admin/employees/$employeeId'
    | '/_admin/admin/projects/$projectId'
    | '/_employee/payslips/$year/$month'
    | '/_admin/admin/employees/'
    | '/_admin/admin/payroll/'
    | '/_admin/admin/projects/'
    | '/_admin/admin/payroll/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_employee': {
      id: '/_employee'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_employee/': {
      id: '/_employee/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/projects': {
      id: '/_employee/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof EmployeeProjectsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/payslips': {
      id: '/_employee/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof EmployeePayslipsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/leave': {
      id: '/_employee/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof EmployeeLeaveRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/attendance': {
      id: '/_employee/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_employee/payslips/': {
      id: '/_employee/payslips/'
      path: '/'
      fullPath: '/payslips/'
      preLoaderRoute: typeof EmployeePayslipsIndexRouteImport
      parentRoute: typeof EmployeePayslipsRoute
    }
    '/_employee/attendance/': {
      id: '/_employee/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof EmployeeAttendanceIndexRouteImport
      parentRoute: typeof EmployeeAttendanceRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_employee/attendance/log': {
      id: '/_employee/attendance/log'
      path: '/log'
      fullPath: '/attendance/log'
      preLoaderRoute: typeof EmployeeAttendanceLogRouteImport
      parentRoute: typeof EmployeeAttendanceRoute
    }
    '/_employee/attendance/$date': {
      id: '/_employee/attendance/$date'
      path: '/$date'
      fullPath: '/attendance/$date'
      preLoaderRoute: typeof EmployeeAttendanceDateRouteImport
      parentRoute: typeof EmployeeAttendanceRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/projects': {
      id: '/_admin/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminAdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/payroll': {
      id: '/_admin/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminAdminPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/leave': {
      id: '/_admin/admin/leave'
      path: '/admin/leave'
      fullPath: '/admin/leave'
      preLoaderRoute: typeof AdminAdminLeaveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/employees': {
      id: '/_admin/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminAdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/attendance': {
      id: '/_admin/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/projects/': {
      id: '/_admin/admin/projects/'
      path: '/'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminAdminProjectsIndexRouteImport
      parentRoute: typeof AdminAdminProjectsRoute
    }
    '/_admin/admin/payroll/': {
      id: '/_admin/admin/payroll/'
      path: '/'
      fullPath: '/admin/payroll/'
      preLoaderRoute: typeof AdminAdminPayrollIndexRouteImport
      parentRoute: typeof AdminAdminPayrollRoute
    }
    '/_admin/admin/employees/': {
      id: '/_admin/admin/employees/'
      path: '/'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminAdminEmployeesIndexRouteImport
      parentRoute: typeof AdminAdminEmployeesRoute
    }
    '/_employee/payslips/$year/$month': {
      id: '/_employee/payslips/$year/$month'
      path: '/$year/$month'
      fullPath: '/payslips/$year/$month'
      preLoaderRoute: typeof EmployeePayslipsYearMonthRouteImport
      parentRoute: typeof EmployeePayslipsRoute
    }
    '/_admin/admin/projects/$projectId': {
      id: '/_admin/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminAdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminAdminProjectsRoute
    }
    '/_admin/admin/employees/$employeeId': {
      id: '/_admin/admin/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/admin/employees/$employeeId'
      preLoaderRoute: typeof AdminAdminEmployeesEmployeeIdRouteImport
      parentRoute: typeof AdminAdminEmployeesRoute
    }
    '/_admin/admin/payroll/$year/$month': {
      id: '/_admin/admin/payroll/$year/$month'
      path: '/$year/$month'
      fullPath: '/admin/payroll/$year/$month'
      preLoaderRoute: typeof AdminAdminPayrollYearMonthRouteImport
      parentRoute: typeof AdminAdminPayrollRoute
    }
  }
}

interface AdminAdminEmployeesRouteChildren {
  AdminAdminEmployeesEmployeeIdRoute: typeof AdminAdminEmployeesEmployeeIdRoute
  AdminAdminEmployeesIndexRoute: typeof AdminAdminEmployeesIndexRoute
}

const AdminAdminEmployeesRouteChildren: AdminAdminEmployeesRouteChildren = {
  AdminAdminEmployeesEmployeeIdRoute: AdminAdminEmployeesEmployeeIdRoute,
  AdminAdminEmployeesIndexRoute: AdminAdminEmployeesIndexRoute,
}

const AdminAdminEmployeesRouteWithChildren =
  AdminAdminEmployeesRoute._addFileChildren(AdminAdminEmployeesRouteChildren)

interface AdminAdminPayrollRouteChildren {
  AdminAdminPayrollIndexRoute: typeof AdminAdminPayrollIndexRoute
  AdminAdminPayrollYearMonthRoute: typeof AdminAdminPayrollYearMonthRoute
}

const AdminAdminPayrollRouteChildren: AdminAdminPayrollRouteChildren = {
  AdminAdminPayrollIndexRoute: AdminAdminPayrollIndexRoute,
  AdminAdminPayrollYearMonthRoute: AdminAdminPayrollYearMonthRoute,
}

const AdminAdminPayrollRouteWithChildren =
  AdminAdminPayrollRoute._addFileChildren(AdminAdminPayrollRouteChildren)

interface AdminAdminProjectsRouteChildren {
  AdminAdminProjectsProjectIdRoute: typeof AdminAdminProjectsProjectIdRoute
  AdminAdminProjectsIndexRoute: typeof AdminAdminProjectsIndexRoute
}

const AdminAdminProjectsRouteChildren: AdminAdminProjectsRouteChildren = {
  AdminAdminProjectsProjectIdRoute: AdminAdminProjectsProjectIdRoute,
  AdminAdminProjectsIndexRoute: AdminAdminProjectsIndexRoute,
}

const AdminAdminProjectsRouteWithChildren =
  AdminAdminProjectsRoute._addFileChildren(AdminAdminProjectsRouteChildren)

interface AdminRouteChildren {
  AdminAdminAttendanceRoute: typeof AdminAdminAttendanceRoute
  AdminAdminEmployeesRoute: typeof AdminAdminEmployeesRouteWithChildren
  AdminAdminLeaveRoute: typeof AdminAdminLeaveRoute
  AdminAdminPayrollRoute: typeof AdminAdminPayrollRouteWithChildren
  AdminAdminProjectsRoute: typeof AdminAdminProjectsRouteWithChildren
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAttendanceRoute: AdminAdminAttendanceRoute,
  AdminAdminEmployeesRoute: AdminAdminEmployeesRouteWithChildren,
  AdminAdminLeaveRoute: AdminAdminLeaveRoute,
  AdminAdminPayrollRoute: AdminAdminPayrollRouteWithChildren,
  AdminAdminProjectsRoute: AdminAdminProjectsRouteWithChildren,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface EmployeeAttendanceRouteChildren {
  EmployeeAttendanceDateRoute: typeof EmployeeAttendanceDateRoute
  EmployeeAttendanceLogRoute: typeof EmployeeAttendanceLogRoute
  EmployeeAttendanceIndexRoute: typeof EmployeeAttendanceIndexRoute
}

const EmployeeAttendanceRouteChildren: EmployeeAttendanceRouteChildren = {
  EmployeeAttendanceDateRoute: EmployeeAttendanceDateRoute,
  EmployeeAttendanceLogRoute: EmployeeAttendanceLogRoute,
  EmployeeAttendanceIndexRoute: EmployeeAttendanceIndexRoute,
}

const EmployeeAttendanceRouteWithChildren =
  EmployeeAttendanceRoute._addFileChildren(EmployeeAttendanceRouteChildren)

interface EmployeePayslipsRouteChildren {
  EmployeePayslipsIndexRoute: typeof EmployeePayslipsIndexRoute
  EmployeePayslipsYearMonthRoute: typeof EmployeePayslipsYearMonthRoute
}

const EmployeePayslipsRouteChildren: EmployeePayslipsRouteChildren = {
  EmployeePayslipsIndexRoute: EmployeePayslipsIndexRoute,
  EmployeePayslipsYearMonthRoute: EmployeePayslipsYearMonthRoute,
}

const EmployeePayslipsRouteWithChildren =
  EmployeePayslipsRoute._addFileChildren(EmployeePayslipsRouteChildren)

interface EmployeeRouteChildren {
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRouteWithChildren
  EmployeeLeaveRoute: typeof EmployeeLeaveRoute
  EmployeePayslipsRoute: typeof EmployeePayslipsRouteWithChildren
  EmployeeProjectsRoute: typeof EmployeeProjectsRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeAttendanceRoute: EmployeeAttendanceRouteWithChildren,
  EmployeeLeaveRoute: EmployeeLeaveRoute,
  EmployeePayslipsRoute: EmployeePayslipsRouteWithChildren,
  EmployeeProjectsRoute: EmployeeProjectsRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
